enum ObjCType {
  static let signedChar = CChar(UnicodeScalar("c").value)
  static let signedShort = CChar(UnicodeScalar("s").value)
  static let signedInt = CChar(UnicodeScalar("i").value)
  static let signedLong = CChar(UnicodeScalar("l").value)
  static let signedLongLong = CChar(UnicodeScalar("q").value)
  static let unsignedChar = CChar(UnicodeScalar("C").value)
  static let unsignedShort = CChar(UnicodeScalar("S").value)
  static let unsignedInt = CChar(UnicodeScalar("I").value)
  static let unsignedLong = CChar(UnicodeScalar("L").value)
  static let unsignedLongLong = CChar(UnicodeScalar("Q").value)
  static let float = CChar(UnicodeScalar("f").value)
  static let double = CChar(UnicodeScalar("d").value)
  static let bool = CChar(UnicodeScalar("B").value)
  static let signedInt128 = CChar(UnicodeScalar("j").value)
  static let unsignedInt128 = CChar(UnicodeScalar("J").value)
  static let signedBitInt128 = CChar(UnicodeScalar("t").value)
  static let unsignedBitInt128 = CChar(UnicodeScalar("T").value)
}
